# Generated by Django 3.2.11 on 2022-01-31 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchangeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foreigncurrency',
            name='total_realized_profit',
            field=models.FloatField(default=0),
        ),
    ]
