# Generated by Django 3.2.11 on 2022-01-30 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('masterinfoapp', '0002_alter_assetmaster_asset_type'),
        ('portfolioapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_paid_amount', models.FloatField(default=0)),
                ('total_amount', models.FloatField(default=0)),
                ('total_cash_amount', models.FloatField(default=0)),
                ('total_realized_profit_amount', models.FloatField(default=0)),
                ('total_valuation_profit_amount', models.FloatField(default=0)),
                ('rate_of_return', models.FloatField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pension', to=settings.AUTH_USER_MODEL)),
                ('pension_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pension_master', to='masterinfoapp.pensionmaster')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pension', to='portfolioapp.portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='PensionTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('PAY', '납입'), ('RECEIVE', '수령')], max_length=20)),
                ('amount', models.FloatField(default=0)),
                ('transaction_date', models.DateTimeField()),
                ('creation_date', models.DateTimeField(auto_now=True)),
                ('last_update_date', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pension_transaction', to=settings.AUTH_USER_MODEL)),
                ('pension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pension_transaction', to='pensionapp.pension')),
            ],
        ),
    ]
