# Generated by Django 3.2.11 on 2022-01-30 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pensionapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pension',
            old_name='total_valuation_profit_amount',
            new_name='total_profit_amount',
        ),
        migrations.RemoveField(
            model_name='pension',
            name='total_realized_profit_amount',
        ),
    ]
