# Generated by Django 3.2.11 on 2022-01-31 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pensionapp', '0003_pension_current_risk_asset_ratio'),
    ]

    operations = [
        migrations.AddField(
            model_name='pension',
            name='total_received_amount',
            field=models.FloatField(default=0),
        ),
    ]
