# Generated by Django 3.2.11 on 2022-01-31 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pensionapp', '0004_pension_total_received_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='pension',
            name='net_paid_amount',
            field=models.FloatField(default=0),
        ),
    ]
