# Generated by Django 3.2.11 on 2022-01-30 15:44

import assetapp.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masterinfoapp', '0002_alter_assetmaster_asset_type'),
        ('portfolioapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('BUY', '매수'), ('SELL', '매도'), ('DIVIDEND', '배당금'), ('SPLIT', '액면분할')], max_length=20)),
                ('quantity', assetapp.models.MinValueFloat(default=0)),
                ('price', assetapp.models.MinValueFloat(default=0)),
                ('dividend_amount', assetapp.models.MinValueFloat(default=0, null=True)),
                ('split_ratio_one_to_N', assetapp.models.MinValueFloat(default=1)),
                ('transaction_fee', assetapp.models.MinValueFloat(default=0, null=True)),
                ('transaction_tax', models.FloatField(default=0, null=True)),
                ('note', models.CharField(default=' - ', max_length=100, null=True)),
                ('applied_flag', models.BooleanField(default=False)),
                ('transaction_date', models.DateTimeField()),
                ('creation_date', models.DateTimeField(auto_now=True)),
                ('last_update_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=0)),
                ('trade_stack_for_fifo', assetapp.models.ListField(null=True, token=',')),
                ('total_amount', models.FloatField(default=0)),
                ('total_realized_profit_amount', models.FloatField(default=0)),
                ('total_dividend_amount', models.FloatField(default=0)),
                ('average_purchase_price_mv', models.FloatField(default=0)),
                ('average_purchase_price_fifo', models.FloatField(default=0)),
                ('total_valuation_profit_amount_mv', models.FloatField(default=0)),
                ('total_valuation_profit_amount_fifo', models.FloatField(default=0)),
                ('rate_of_return_mv', models.FloatField(default=0)),
                ('rate_of_return_fifo', models.FloatField(default=0)),
                ('asset_master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_master', to='masterinfoapp.assetmaster')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to='portfolioapp.portfolio')),
            ],
        ),
    ]
