# Generated by Django 3.2.11 on 2022-02-07 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetapp', '0004_alter_assettransaction_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='position_opened_flag',
            field=models.BooleanField(default=True),
        ),
    ]
