# Generated by Django 3.2.11 on 2022-02-12 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetapp', '0005_asset_position_opened_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell'), ('DIVIDEND', 'Dividend'), ('SPLIT', 'Split')], max_length=20),
        ),
    ]
