# Generated by Django 3.2.11 on 2022-02-14 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetapp', '0006_alter_assettransaction_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='total_amount_exchanged',
            field=models.FloatField(default=0),
        ),
    ]
