# Generated by Django 3.2.11 on 2022-02-12 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('masterinfoapp', '0012_auto_20220207_2127'),
        ('dashboardapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Liquidity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liquidity_type', models.CharField(choices=[('DEPOSIT', 'Bank Deposit'), ('CMA', "IB's CMA"), ('INSTALLMENT', 'Installment Saving'), ('VOUCHER', 'Voucher'), ('FOREIGN_CURRENCY', 'Foreign Currency')], max_length=100)),
                ('liquidity_name', models.CharField(default='Liquidity', max_length=100)),
                ('amount', models.FloatField(default=0)),
                ('creation_date', models.DateTimeField(auto_now=True)),
                ('last_update_date', models.DateTimeField(auto_now_add=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liquidity', to='masterinfoapp.currencymaster')),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liquidity', to='dashboardapp.dashboard')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liquidity', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
