# Generated by Django 3.2.11 on 2022-02-12 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('householdbookapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidity',
            name='amount_exchanged',
            field=models.FloatField(default=0),
        ),
    ]
