# Generated by Django 3.2.11 on 2022-02-12 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterinfoapp', '0012_auto_20220207_2127'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboardapp', '0001_initial'),
        ('householdbookapp', '0002_liquidity_amount_exchanged'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debt_name', models.CharField(default='debt', max_length=100)),
                ('long_term_debt_flag', models.BooleanField(default=False)),
                ('amount', models.FloatField(default=0)),
                ('amount_exchanged', models.FloatField(default=0)),
                ('creation_date', models.DateTimeField(auto_now=True)),
                ('last_update_date', models.DateTimeField(auto_now_add=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debt', to='masterinfoapp.currencymaster')),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debt', to='dashboardapp.dashboard')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debt', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
