# Generated by Django 3.2.11 on 2022-02-13 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboardapp', '0001_initial'),
        ('householdbookapp', '0003_debt'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_name', models.DateTimeField()),
                ('total_income_amount', models.FloatField(default=0)),
                ('income_labor', models.FloatField(default=0)),
                ('income_capital', models.FloatField(default=0)),
                ('income_etc', models.FloatField(default=0)),
                ('total_expense_amount', models.FloatField(default=0)),
                ('expense_housing_communication', models.FloatField(default=0)),
                ('expense_living', models.FloatField(default=0)),
                ('expense_grocery', models.FloatField(default=0)),
                ('expense_shopping', models.FloatField(default=0)),
                ('expense_leisure', models.FloatField(default=0)),
                ('expense_health', models.FloatField(default=0)),
                ('expense_largess', models.FloatField(default=0)),
                ('expense_transportation', models.FloatField(default=0)),
                ('expense_alcohol', models.FloatField(default=0)),
                ('expense_education', models.FloatField(default=0)),
                ('expense_car', models.FloatField(default=0)),
                ('expense_financial', models.FloatField(default=0)),
                ('expense_love_affair', models.FloatField(default=0)),
                ('expense_etc', models.FloatField(default=0)),
                ('total_savings_amount', models.FloatField(default=0)),
                ('monthly_savings_rate', models.FloatField(default=0)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_expense', to='dashboardapp.dashboard')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_expense', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
