# Generated by Django 3.2.11 on 2022-02-22 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('householdbookapp', '0007_auto_20220222_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='buynowpaylater',
            name='nominal_monthly_payment_amount',
            field=models.FloatField(default=0),
        ),
    ]
