# Generated by Django 3.2.11 on 2022-02-22 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterinfoapp', '0012_auto_20220207_2127'),
        ('householdbookapp', '0008_buynowpaylater_nominal_monthly_payment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='buynowpaylater',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='buy_now_pay_later', to='masterinfoapp.currencymaster'),
            preserve_default=False,
        ),
    ]
