# Generated by Django 3.2.11 on 2022-01-31 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TempTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_source', models.CharField(max_length=100)),
                ('asset_type', models.CharField(max_length=20)),
                ('transaction_type', models.CharField(max_length=100)),
                ('ticker', models.CharField(max_length=20)),
                ('pension_type', models.CharField(max_length=20)),
                ('currency', models.CharField(max_length=20)),
                ('quantity', models.FloatField(default=0)),
                ('price', models.FloatField(default=0)),
                ('exchange_rate', models.FloatField(default=0)),
                ('transaction_fee', models.FloatField(default=0)),
                ('transaction_tax', models.FloatField(default=0)),
                ('split_ratio_one_to_N', models.FloatField(default=0)),
                ('transaction_date', models.DateTimeField()),
                ('applied_flag', models.BooleanField(default=False)),
                ('applied_date', models.DateTimeField(null=True)),
                ('creation_date', models.DateTimeField(auto_now=True)),
                ('last_update_date', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp_transaction', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
