# Generated by Django 3.2.11 on 2022-02-14 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboardapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capture_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_asset_amount', models.FloatField(default=0, null=True)),
                ('total_liquidity_amount', models.FloatField(default=0, null=True)),
                ('total_investment_amount', models.FloatField(default=0, null=True)),
                ('total_debt_amount', models.FloatField(default=0, null=True)),
                ('net_capital_amount', models.FloatField(default=0, null=True)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_capture', to='dashboardapp.dashboard')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_capture', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
