# Generated by Django 3.2.11 on 2022-01-30 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_code', models.CharField(max_length=10)),
                ('currency_name', models.CharField(max_length=100)),
                ('currency_sign', models.CharField(max_length=10, null=True)),
                ('currency_national_flag', models.ImageField(null=True, upload_to='currencymaster/')),
            ],
        ),
        migrations.CreateModel(
            name='PensionMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pension_type', models.CharField(max_length=100)),
                ('pension_name', models.CharField(max_length=100)),
                ('risk_ratio_force_flag', models.BooleanField(default=False)),
                ('risk_ratio', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='AssetMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('EQUITY', 'Equity'), ('GUARDIAN', 'Guardian'), ('REITS', 'Reits'), ('PENSION', 'Pension'), ('CRYPTO', 'Crypto Asset')], max_length=100, null=True)),
                ('market', models.CharField(choices=[('KSE', 'Korean Stock Exchange(KSE)'), ('NASDAQ', 'NASDAQ'), ('NYSE', 'NewYork Stock Exchange(NYSE)'), ('NA', 'Not Applicable')], max_length=100, null=True)),
                ('ticker', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200, null=True)),
                ('image', models.ImageField(default='static/images/diamond_goose_logo_mk1.png', upload_to='assetmaster/')),
                ('current_price', models.FloatField(default=0)),
                ('pension_asset_flag', models.BooleanField(default=False)),
                ('pension_risk_asset_flag', models.BooleanField(default=False)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_master', to='masterinfoapp.currencymaster')),
            ],
        ),
    ]
