# Generated by Django 3.2.11 on 2022-01-30 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterinfoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetmaster',
            name='asset_type',
            field=models.CharField(choices=[('EQUITY', 'Equity'), ('GUARDIAN', 'Guardian'), ('REITS', 'Reits'), ('PENSION_ASSET', 'Pension Asset'), ('CRYPTO', 'Crypto Asset')], max_length=100, null=True),
        ),
    ]
