# Generated by Django 3.2.11 on 2022-01-31 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterinfoapp', '0002_alter_assetmaster_asset_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencymaster',
            name='current_exchange_rate',
            field=models.FloatField(default=0),
        ),
    ]
