# Generated by Django 3.2.11 on 2022-02-05 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterinfoapp', '0004_remove_currencymaster_current_exchange_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencymaster',
            name='country',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
