# Generated by Django 3.2.11 on 2022-02-06 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterinfoapp', '0005_currencymaster_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetmaster',
            name='etf_flag',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
