# Generated by Django 3.2.11 on 2022-02-05 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterinfoapp', '0006_alter_currencymaster_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencymaster',
            name='country',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
