# Generated by Django 3.2.11 on 2022-02-07 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterinfoapp', '0008_assettypemaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='assettypemaster',
            name='text_color_hex',
            field=models.CharField(default='#081321', max_length=7),
        ),
    ]
