# Generated by Django 3.2.11 on 2022-02-07 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterinfoapp', '0009_assettypemaster_text_color_hex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assettypemaster',
            name='asset_type_code',
            field=models.CharField(max_length=30),
        ),
    ]
