# Generated by Django 3.2.11 on 2022-02-07 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterinfoapp', '0010_alter_assettypemaster_asset_type_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetmaster',
            name='asset_type_master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='masterinfoapp.assettypemaster'),
        ),
    ]
